#pragma once

#include "quantum.h"

/* Custom keycodes */
enum x240_keycodes {
    CK_BKLT = SAFE_RANGE,  /* Toggle keyboard backlight */
    CK_FNLK,               /* Toggle FN Lock (permanently invert FN layer) */
};

/* Layer indices */
enum x240_layers {
    _BASE = 0,
    _FN,
};

/*
 * LAYOUT is generated by QMK from keyboard.json ("layouts"), which currently
 * describes the historical 8 x 13 placeholder inside the 10 x 24 matrix.
 * Issue #38 regenerates that block from the measured pinout.
 */
